### PR TITLE
Update for 4.x indexes API (closes #45)

### LINKED ISSUE #45: Get indexes working with new index spec in 4.x
see https://github.com/silverstripe/silverstripe-framework/pull/6930

### PR DESCRIPTION
**Pull request by kinglozzer**

### CODE REVIEW

**Comment by NightJar** [comment]
CI being broken certainly doesn't help :(

**Comment by kinglozzer** [comment]
I’ve made some progress repairing the CI builds. A lot of failures (probably related to https://github.com/kinglozzer/silverstripe-mssql/commit/586dac5358f792adb4a94e4d4c137027bff443e1) and a fatal error with CSV parsing that I guess must be Windows-related 😕

**Comment by NightJar** [comment]
related: https://github.com/silverstripe/silverstripe-framework/issues/7974

**Comment by NightJar** [comment]
I'm afraid it's no go ol' chap... because most unfortunately you've removed the critical parts to complete the implementation of the `abstract` superclass in https://github.com/silverstripe/silverstripe-mssql/commit/321b9fe89092bd7aa26a418829a5f2f06fca67ce
:>

**Comment by kinglozzer** [comment]
That’s `master` I believe, the 2.0 branch and this pull request should be fine

**Comment by NightJar** [comment]
Ah. Of course, you've updated the branch alias since then too 😅 

I submit an argument that the 2.0 tag is wrong :P
As is the 2.0.1 tag, in that neither are even functional, let alone bug free enough to warrant release tags.
But never mind, we're here now.

I think that the generator work (the only thing that master is ahead with) is fine to be in the 2.x release line, in that it's modifying (repairing!) existing functionality, rather than altering the public API.
But that's by the by.

I'll re-test against the 2.0 branch :)

**Comment by kinglozzer** [comment]
Yeah I was just going to create a `2` branch, but then someone needs to remember to branch off a `2.0` branch _before_ merging any new features... easily forgotten. Point taken about `2.0.1`, at the time I thought it was just the installer that was broken but should’ve checked!

The generator work isn’t compatible with SilverStripe 4, so that can’t go in 2.x. That’s why I created a `2`/`2.0` branch - because we didn’t have a 4-compatible release line 😅

**Comment by NightJar** [comment]
Not compatible with 4? :o
What prevents that?
Perhaps should bump the master requirements to framework 5.x-dev?

But yeah, this whole module has been in need of some love for some time I think.

In other news though, by gosh you've done it good lad :D
Site now successfully completes a dev/build.

Cheeky delete tag and re-tag 2.0.0? :P :trollface: 

But seriously, this could probably be tagged. Depends on how much testing we feel like we should submit the adapter to... since the unit tests are all but useless in that they test the DBDatetime more than they do the adapter itself :<
And the CI is broken so we can't even tell if a dev/build to be able to run the tests works...

In any case, *This should be merged*.

**Comment by kinglozzer** [comment]
I’m going to break the self-merge rule given that I’ve now got @NightJar’s blessing (and this module is currently broken in SS4)

**Comment by kinglozzer** [comment]
Added an issue for the test failures here https://github.com/silverstripe/silverstripe-mssql/issues/53

**Pull request merged**
